version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TEST_DB_USER=root
      - TEST_DB_PASSWORD=p@ssword
      - TEST_DB_HOST=db
      - TEST_DB_NAME=sample_test
    volumes:
      - .:/app
      - phx-node_modules:/app/assets/node_modules
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - phx-network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssword
      - MYSQL_DATABASE=sample_dev
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=p@ssword
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldb-local_data:/var/lib/mysql
    ports:
      - 4306:4306
    networks:
      - phx-network

volumes:
  mysqldb-local_data:
  phx-node_modules:

networks:
  phx-network:
    driver: bridge
